=== alex-tw-lam/tfschema/tests/6-terraschema-compat/28-terraschema-custom-validation/test.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "a_list_maximum_minimum_length": {
      "type": "array",
      "description": "A list variable that must have a length greater than 0 and less than 10",
      "default": [
        "a"
      ],
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 9
    },
    "a_number_enum_kind_1": {
      "type": "number",
      "description": "A number variable that must be one of the values 1, 2, or 3",
      "default": 1,
      "enum": [
        1,
        2,
        3
      ]
    },
    "a_number_enum_kind_2": {
      "type": "number",
      "description": "A number variable that must be one of the values 1, 2, or 3",
      "default": 1,
      "enum": [
        1,
        2,
        3
      ]
    },
    "a_number_exclusive_maximum_minimum": {
      "type": "number",
      "description": "A number variable that must be greater than 0 and less than 10",
      "default": 1,
      "exclusiveMinimum": 0,
      "exclusiveMaximum": 10
    },
    "a_number_maximum_minimum": {
      "type": "number",
      "description": "A number variable that must be between 0 and 10 (inclusive)",
      "default": 0,
      "minimum": 0,
      "maximum": 10
    },
    "a_string_enum_kind_1": {
      "type": "string",
      "description": "A string variable that must be one of the values 'a', 'b', or 'c'",
      "default": "a",
      "enum": [
        "a",
        "b",
        "c"
      ]
    },
    "a_string_enum_kind_2": {
      "type": "string",
      "description": "A string variable that must be one of the values 'a', 'b', or 'c'",
      "default": "a",
      "enum": [
        "a",
        "b",
        "c"
      ]
    },
    "a_string_maximum_minimum_length": {
      "type": "string",
      "description": "A string variable that must have a length less than 10 and greater than 0",
      "default": "a",
      "maxLength": 9
    },
    "a_string_pattern_1": {
      "type": "string",
      "description": "A string variable that must be a valid IPv4 address",
      "default": "1.1.1.1",
      "pattern": "^[0-9]{1,3}(\\.[0-9]{1,3}){3}$"
    },
    "a_string_pattern_2": {
      "type": "string",
      "description": "string that must be a valid colour hex code in the form #RRGGBB",
      "default": "#000000",
      "pattern": "^#[0-9a-fA-F]{6}$"
    },
    "a_string_set_length": {
      "type": "string",
      "description": "A string variable that must have length 4",
      "default": "abcd"
    }
  },
  "required": [],
  "additionalProperties": true
}

=== alex-tw-lam/tfschema/tests/6-terraschema-compat/28-terraschema-custom-validation/test.tfvar.json
{
  "a_string_enum_kind_1": "b",
  "a_string_enum_kind_2": "c",
  "a_number_enum_kind_1": 2,
  "a_number_enum_kind_2": 3,
  "a_number_exclusive_maximum_minimum": 5,
  "a_number_maximum_minimum": 5,
  "a_list_maximum_minimum_length": ["item1", "item2", "item3"],
  "a_string_maximum_minimum_length": "test123",
  "a_string_set_length": "abcd",
  "a_string_pattern_1": "192.168.1.1",
  "a_string_pattern_2": "#FF5733"
}
